[bastion]
bastion_host ansible_host=13.223.71.102 ansible_user=ubuntu

[webservers]
web1 ansible_host=10.0.142.42 ansible_user=ubuntu
web2 ansible_host=10.0.156.88 ansible_user=ubuntu

[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@13.223.71.102"'
